# Generated by Django 3.0.1 on 2021-04-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffsShoreCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('afm', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffsShoreCostumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, null=True, verbose_name='Επωνυμια')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='Διευθυνση')),
                ('job_description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Επαγγελμα')),
                ('loading_place', models.CharField(blank=True, default='Εδρα μας', max_length=240, null=True, verbose_name='Τοπος Φορτωσης')),
                ('destination', models.CharField(blank=True, default='Εδρα του,', max_length=240, null=True, verbose_name='Προορισμος')),
                ('afm', models.CharField(blank=True, max_length=10, null=True, verbose_name='ΑΦΜ')),
                ('doy', models.CharField(blank=True, default='Σπαρτη', max_length=240, null=True, verbose_name='ΔΟΥ')),
                ('destination_city', models.CharField(blank=True, max_length=240, null=True, verbose_name='Πολη')),
                ('transport', models.CharField(blank=True, max_length=10, null=True, verbose_name='Μεταφορικο Μεσο')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Ονομα')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Επιθετο')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Σημειώσεις')),
                ('cellphone', models.CharField(blank=True, max_length=20, verbose_name='Κινητό')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργός')),
            ],
            options={
                'ordering': ['title', 'afm'],
            },
        ),
        migrations.CreateModel(
            name='OffsShoreCompanyCostumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OffsShoreCostumers.OffsShoreCompany')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OffsShoreCostumers.OffsShoreCostumer')),
            ],
        ),
        migrations.CreateModel(
            name='OffshorePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='OffsShoreCostumers.OffsShoreCompanyCostumer', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OffshoreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OffsShoreCostumers.OffsShoreCompanyCostumer', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
