# Generated by Django 3.0.1 on 2021-04-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffsShoreCostumers', '0002_auto_20210426_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsshorecompanycostumer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OffsShoreCostumers.OffsShoreCompany'),
        ),
        migrations.AlterField(
            model_name='offsshorecompanycostumer',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OffsShoreCostumers.OffsShoreCostumer'),
        ),
    ]
