# Generated by Django 2.2.4 on 2021-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='final_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxes_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Φορος'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Καθαρή Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='clean_value',
            field=models.DecimalField(decimal_places=3, max_digits=17, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ποσο Εκπτωσης'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_clean_value',
            field=models.DecimalField(decimal_places=3, max_digits=17, verbose_name='Καθαρη Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=17, verbose_name='Τιμή'),
        ),
    ]
