# Generated by Django 3.0.1 on 2020-04-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0002_auto_20200416_0952'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Κλειδωμενο'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Κωδικος Τιμολογιου'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_settings.PaymentMethod', verbose_name='Τροπος Πληρωμής'),
        ),
    ]
