# Generated by Django 3.0.1 on 2020-04-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_auto_20200402_1457'),
        ('catalogue', '0002_auto_20200330_2053'),
        ('project_settings', '0001_initial'),
        ('warehouse', '0002_auto_20200331_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='catalogue.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Κοστολογηση'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumers.Costumer', verbose_name='Πελατης'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνια'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Μετασχηματισμενο'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_settings.PaymentMethod', verbose_name='Τροπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ονομασια'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Αξια'),
        ),
    ]
