# Generated by Django 2.2 on 2020-03-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
        ('catalogue', '0003_product_taxes_modifier'),
        ('warehouse', '0003_auto_20200315_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTransformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumers.Costumer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransformationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=17)),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.InvoiceTransformation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransformationIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.InvoiceTransformationItem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product')),
            ],
        ),
    ]
