# Generated by Django 3.0.4 on 2020-04-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200402_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Vendor', verbose_name='Προμηθευτης'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Πληρωμενο;'),
        ),
    ]
