# Generated by Django 2.2 on 2020-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_invoicetransformation_invoicetransformationingredient_invoicetransformationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransformation',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
