# Generated by Django 3.0.1 on 2020-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0009_auto_20200406_1546'),
        ('warehouse', '0004_auto_20200403_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransformation',
            name='costumer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='costumers.Costumer', verbose_name='Πελατης'),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Παρτιδα Εμφαλωσης'),
        ),
    ]
