# Generated by Django 2.2.4 on 2021-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20210129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Κωδικος Τιμολογιου'),
        ),
    ]
