# Generated by Django 3.0.1 on 2020-04-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0011_auto_20200406_1551'),
        ('warehouse', '0005_auto_20200406_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransformation',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costumers.Costumer', verbose_name='Πελατης'),
        ),
    ]
