# Generated by Django 2.2 on 2020-03-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_taxes_modifier'),
        ('warehouse', '0005_invoicetransformation_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransformationingredient',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductStorage'),
        ),
        migrations.AddField(
            model_name='invoicetransformationitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductStorage'),
        ),
    ]
