# Generated by Django 3.0.4 on 2020-04-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200406_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='used_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Χρησιμοποιημενη Ποσοτητα'),
        ),
        migrations.AddField(
            model_name='invoicetransformationitem',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.InvoiceItem'),
        ),
    ]
