# Generated by Django 2.2 on 2020-03-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200316_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetransformationitem',
            name='cost',
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transf_ingre', to='warehouse.InvoiceTransformationItem'),
        ),
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_ingre', to='catalogue.ProductStorage'),
        ),
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_items', to='catalogue.ProductStorage'),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
