# Generated by Django 3.0.1 on 2021-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_merge_20210422_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνια Τιμολογίου'),
        ),
    ]
