# Generated by Django 3.0.4 on 2020-04-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20200406_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetransformationitem',
            name='invoice_item',
        ),
        migrations.AddField(
            model_name='invoicetransformationingredient',
            name='warehouse_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.InvoiceItem'),
        ),
    ]
