# Generated by Django 2.2 on 2020-03-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20200316_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Αξία'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Καθαρή Αξια'),
        ),
    ]
