# Generated by Django 3.0.4 on 2020-04-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20200406_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransformationingredient',
            name='warehouse_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='warehouse.InvoiceItem'),
        ),
    ]
