# Generated by Django 3.0.1 on 2020-04-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20200407_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransformationitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicetransformationitem',
            name='used_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
