# Generated by Django 2.2 on 2020-03-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_invoice_taxes_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_invoices', to='catalogue.ProductStorage'),
        ),
    ]
