# Generated by Django 3.0.1 on 2020-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20200327_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransformationingredient',
            name='qty_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Ποσοτητσ'),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Αξια'),
        ),
    ]
