# Generated by Django 3.0.1 on 2020-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20200408_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransformationitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνια λήξης'),
        ),
    ]
