# Generated by Django 3.0.4 on 2020-04-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200405_1349'),
        ('warehouse', '0011_invoicetransformationitem_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_invoices', to='catalogue.ProductStorage', verbose_name='Αποθηκη'),
        ),
    ]
