# Generated by Django 3.0.4 on 2020-03-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20200330_1526'),
        ('warehouse', '0012_invoicetransformation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Ποσοτητα'),
        ),
        migrations.AlterField(
            model_name='invoicetransformationitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_items', to='catalogue.ProductStorage', verbose_name='Αποθηκη'),
        ),
    ]
