# Generated by Django 3.0.4 on 2020-04-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200405_1349'),
        ('warehouse', '0012_auto_20200413_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseMovementsInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνια')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Τιτλος')),
                ('order_type', models.CharField(choices=[('a', 'Παραστατικο Εισαγωγής'), ('b', 'Παραστατικο Εξαγωγης')], max_length=1, verbose_name='Ειδος')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseMovementInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Ποσοτητα')),
                ('value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Συνολική Αξια')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseMovementsInvoice', verbose_name='Παραστατικο')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product', verbose_name='Προϊον')),
                ('storage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductStorage', verbose_name='Αποθηκη')),
            ],
        ),
    ]
