# Generated by Django 3.0.1 on 2020-04-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20200414_0829'),
        ('warehouse', '0014_auto_20200413_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemovementinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ware_movements', to='catalogue.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='warehousemovementinvoiceitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ware_storage_movements', to='catalogue.ProductStorage', verbose_name='Αποθηκη'),
        ),
    ]
