# Generated by Django 2.2 on 2020-03-16 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 59, 44, 202487, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
