# Generated by Django 2.2.4 on 2021-01-23 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20200424_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 14, 1, 50, 484643, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
