# Generated by Django 2.2 on 2020-03-16 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20200316_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 9, 10, 4, 486844, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
