# Generated by Django 3.0.1 on 2020-03-31 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20200331_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 13, 5, 0, 872643, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
