# Generated by Django 3.0.1 on 2020-04-02 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0003_auto_20200331_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 57, 31, 718538, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
