# Generated by Django 3.0.1 on 2021-01-25 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0003_auto_20210123_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 5, 2, 56, 167264, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
