# Generated by Django 3.0.4 on 2020-04-03 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
        ('costumers', '0004_auto_20200402_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerpayment',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Πληρωμενο'),
        ),
        migrations.AlterField(
            model_name='costumerpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_settings.PaymentMethod', verbose_name='Επιταγη'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 12, 5, 9, 892519, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
