# Generated by Django 2.2 on 2020-03-16 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_auto_20200316_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 18, 44, 15, 7337, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
