# Generated by Django 3.0.1 on 2021-01-25 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_auto_20210125_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 5, 3, 5, 884373, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
