# Generated by Django 2.2 on 2020-03-18 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0005_auto_20200316_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 5, 11, 52, 571802, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
