# Generated by Django 3.0.1 on 2021-01-25 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0006_auto_20210125_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 5, 46, 20, 718823, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
