# Generated by Django 2.2.6 on 2020-03-19 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0007_auto_20200319_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 6, 37, 25, 852000, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
