# Generated by Django 3.0.1 on 2020-04-05 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0007_auto_20200405_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 10, 49, 1, 615767, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
