# Generated by Django 2.2.4 on 2021-01-29 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0007_auto_20210125_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 8, 27, 11, 860945, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
