# Generated by Django 3.0.1 on 2021-01-30 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0007_auto_20210125_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 7, 15, 59, 382472, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
