# Generated by Django 2.2.4 on 2021-01-29 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0008_auto_20210129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 8, 29, 27, 596008, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
