# Generated by Django 3.0.1 on 2021-04-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0008_auto_20210130_0915'),
        ('costumers', '0009_auto_20210129_1029'),
    ]

    operations = [
    ]
