# Generated by Django 2.2 on 2020-03-23 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0009_auto_20200323_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='costumers.Costumer', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 6, 33, 24, 43383, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
