# Generated by Django 2.2 on 2020-03-23 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
        ('costumers', '0010_auto_20200323_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_settings.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 9, 2, 34, 229747, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
