# Generated by Django 3.0.1 on 2020-04-06 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0010_auto_20200406_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 12, 51, 7, 153835, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
