# Generated by Django 3.0.1 on 2021-04-22 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0010_merge_20210422_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 4, 29, 26, 209775, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
