# Generated by Django 2.2 on 2020-03-23 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0011_auto_20200323_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 11, 36, 11, 510299, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
