# Generated by Django 3.0.4 on 2020-04-06 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0011_auto_20200406_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 10, 17, 513098, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
