# Generated by Django 3.0.1 on 2021-04-28 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0012_auto_20210426_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 7, 38, 41, 748052, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
