# Generated by Django 2.2 on 2020-03-26 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0013_auto_20200325_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinvoice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 14, 34, 32, 402339, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
