# Generated by Django 2.2 on 2020-03-26 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0014_auto_20200326_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 18, 18, 10, 285980, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
