# Generated by Django 3.0.4 on 2020-04-07 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0014_auto_20200407_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 5, 9, 20, 476169, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
