# Generated by Django 3.0.1 on 2020-04-08 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0015_auto_20200407_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 16, 23, 365987, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
