# Generated by Django 2.2 on 2020-03-27 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0015_auto_20200326_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 13, 21, 26, 849928, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
