# Generated by Django 3.0.1 on 2020-04-08 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0016_auto_20200408_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 25, 32, 49359, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
