# Generated by Django 3.0.1 on 2020-03-28 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0016_auto_20200327_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 5, 37, 21, 266715, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
