# Generated by Django 3.0.1 on 2020-04-12 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0017_auto_20200408_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 11, 49, 46, 215631, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
