# Generated by Django 3.0.1 on 2020-03-28 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0017_auto_20200328_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 12, 24, 14, 443286, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
