# Generated by Django 3.0.4 on 2020-04-13 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0019_auto_20200413_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 7, 47, 22, 870270, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
