# Generated by Django 3.0.1 on 2020-03-29 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0019_auto_20200328_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 6, 47, 25, 333606, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
