# Generated by Django 3.0.4 on 2020-04-13 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0020_auto_20200413_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 33, 15, 994316, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
