# Generated by Django 3.0.4 on 2020-03-30 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0020_auto_20200329_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 12, 26, 20, 297768, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
