# Generated by Django 3.0.1 on 2020-04-14 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0021_auto_20200413_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 29, 44, 36543, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
