# Generated by Django 2.2.6 on 2020-03-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0008_auto_20200319_0837'),
        ('catalogue', '0004_auto_20200318_0711'),
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό')], default='a', max_length=1, verbose_name='ΜΜ')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Ποσότητα')),
                ('value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τιμή')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Εκπτωση')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ποσο Εκπτωσης')),
                ('clean_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια')),
                ('total_clean_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Καθαρη Αξια')),
                ('taxes_modifier', models.IntegerField(default=24, verbose_name='ΦΠΑ')),
                ('taxes_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια ΦΠΑ')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τελικη Αξία')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumers.Costumer', verbose_name='')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='point_of_sale.SalesInvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product', verbose_name='product_items')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.ProductStorage')),
            ],
        ),
        migrations.DeleteModel(
            name='SaleInvoiceItem',
        ),
    ]
