# Generated by Django 2.2 on 2020-03-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_auto_20200319_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='costumers.Costumer', verbose_name='Πελάτης'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Πωληση'), ('b', 'Τιμολογιο')], default='a', max_length=1, verbose_name='Ειδος'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='catalogue.Product', verbose_name='Προϊον'),
        ),
    ]
