# Generated by Django 3.0.4 on 2020-04-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20200407_0805'),
        ('point_of_sale', '0002_auto_20200331_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='warehouse_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.InvoiceTransformationItem'),
        ),
    ]
