# Generated by Django 2.2 on 2020-03-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20200323_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', to='costumers.Costumer', verbose_name='Πελάτης'),
        ),
    ]
