# Generated by Django 3.0.1 on 2020-04-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20200408_0816'),
        ('point_of_sale', '0003_salesinvoiceitem_warehouse_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='warehouse_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_itema', to='warehouse.InvoiceTransformationItem'),
        ),
    ]
