# Generated by Django 3.0.1 on 2020-04-12 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_invoicetransformationitem_expiration_date'),
        ('point_of_sale', '0004_auto_20200408_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='lot',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 14, 50, 2, 667618), verbose_name='Ημερομηνια λήξης'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='lot',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='warehouse_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='warehouse.InvoiceTransformationItem'),
        ),
    ]
