# Generated by Django 2.2 on 2020-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20200323_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='etxra_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Εκπτωση'),
        ),
    ]
