# Generated by Django 2.2 on 2020-03-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_salesinvoice_etxra_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['date']},
        ),
    ]
