# Generated by Django 3.0.1 on 2020-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20200326_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
