# Generated by Django 3.0.4 on 2020-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_salesinvoiceitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
