# Generated by Django 3.0.4 on 2020-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('a', 'Αντικαταβολή'), ('b', 'Τραπεζική ΚατάΘεση')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('warning_max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('warning_low_max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
            ],
        ),
    ]
