# Generated by Django 2.2 on 2020-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Τιτλος')),
                ('category', models.CharField(choices=[('a', 'Αντικαταβολή'), ('b', 'Τραπεζική ΚατάΘεση')], max_length=1, verbose_name='Κατηγορια')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατασταση')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Ονομασια')),
                ('position', models.TextField(blank=True, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Χωρητικοτητα')),
                ('max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Μεγιστη Χωρητικοτητα')),
                ('warning_max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('warning_low_max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
            ],
        ),
    ]
