# Generated by Django 3.0.1 on 2020-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='category',
            field=models.CharField(choices=[('a', 'Αντικαταβολή'), ('b', 'Τραπεζική ΚατάΘεση')], max_length=1, verbose_name='Κατηγορια'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Τιτλος'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατασταση'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Χωρητικοτητα'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Μεγιστη Χωρητικοτητα'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Ονομασια'),
        ),
    ]
