# Generated by Django 3.0.1 on 2020-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warning_low_max_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warning_max_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
