# Generated by Django 2.2 on 2020-03-14 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_offer', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120, verbose_name="'Ονομα προιόντος")),
                ('sku', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή λιανικής')),
                ('margin', models.IntegerField(blank=True, default=30, null=True, verbose_name='Margin')),
                ('markup', models.IntegerField(blank=True, default=30, null=True, verbose_name='Markup')),
                ('price_internet', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Internet(No use)')),
                ('price_b2b', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Χονδρικής')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Εκπτωτική Τιμή.')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Απόθεμα')),
                ('unit', models.CharField(blank=True, choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό')], default='1', max_length=1, null=True)),
                ('safe_stock', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Αγοράς')),
                ('order_discount', models.IntegerField(default=0, verbose_name="'Εκπτωση Τιμολογίου σε %")),
                ('qty_kilo', models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Βάρος/Τεμάχια ανά Συσκευασία ')),
                ('different_color', models.ManyToManyField(blank=True, related_name='_product_different_color_+', to='catalogue.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Ονομασια')),
                ('have_storage', models.BooleanField(default=False, verbose_name='εχει Αποθηκη')),
                ('wholesale_active', models.BooleanField(default=False, verbose_name='Active for WholeSale')),
                ('is_service', models.BooleanField(default=False, verbose_name='Service')),
                ('have_ingredient', models.BooleanField(default=False, verbose_name='Παρασκευη Απο Εμας')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(default=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='catalogue.Product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_settings.Storage')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_value', to='catalogue.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalogue.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductClass'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='catalogue.Product'),
        ),
    ]
