# Generated by Django 2.2 on 2020-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200314_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes_modifier',
            field=models.IntegerField(default=24, verbose_name='ΦΠΑ'),
        ),
    ]
