# Generated by Django 3.0.1 on 2020-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='have_storage',
            field=models.BooleanField(default=False),
        ),
    ]
