# Generated by Django 3.0.1 on 2020-03-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_productclass_have_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductClass'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='have_ingredient',
            field=models.BooleanField(default=False, verbose_name='Παρασκευη Απο Εμας'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='have_storage',
            field=models.BooleanField(default=False, verbose_name='εχει Αποθηκη'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ονομασια'),
        ),
    ]
