# Generated by Django 3.0.1 on 2020-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20200405_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safe_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Ασφαλη Αποθεμα'),
        ),
    ]
