# Generated by Django 3.0.1 on 2021-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20210125_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Τιμή Αγοράς'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_kilo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Βάρος/Τεμάχια ανά Συσκευασία '),
        ),
    ]
