# Generated by Django 3.0.1 on 2020-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200405_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstorage',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Προτεριοτητα'),
        ),
    ]
