# Generated by Django 3.0.1 on 2021-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20210125_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=17, verbose_name='Κοστος'),
        ),
    ]
