# Generated by Django 3.0.1 on 2021-01-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20210125_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
