# Generated by Django 3.0.1 on 2020-04-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Τελική Αξία'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμενο?'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payroll.GenericExpenseCategory', verbose_name='Κατηγορια'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Τελική Αξία'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμενο?'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.GenericExpensePerson', verbose_name='Προσωπο'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Τελική Αξία'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμενο?'),
        ),
    ]
